### ISSUE TITLE
exports support

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-resolve#12]
Now that this is implemented in Node.js `--experimental-modules` we should be able to support package.json `"exports"`. Once we have `"aliases"`, we should be able to deprecate `"map"` for `"exports"` and `"aliases"`.

One hard thing will be supporting the `"browser"` field properly under this model. It's still debateable whether the `"browser"` field object form should support mapping modules if we have differential exports and aliases. Perhaps "map" can remain the greater abstraction, or perhaps we can directly unify on a `"browser"` desugar into aliasing and exports.

**Comment by fusionstrings** [comment]
Actually I figured, most of my monorepo related requirements https://github.com/jspm/jspm-cli/issues/1534 align with this but got a better deal in terms of https://github.com/jspm/jspm-cli/pull/2491 💯 

Thanks for adding it in roadmap. This is super handy. I am looking forward for it.

**Comment by guybedford** [comment]
This was included in https://github.com/jspm/jspm-resolve/pull/13.
